name: Go

on:
  push:
    branches: [main]
    paths:
      - 'go/**'
  pull_request:
    paths:
      - 'go/**'

jobs:
  test:
    name: Run Go Vet and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run go vet
        run: go vet ./...

      - name: Run go test
        run: go test ./...